### ISSUE TITLE
Add Solr extensions from Sematext

### ISSUE THREAD

**Issue by otisg** [solr-extensions/solr-extensions.github.io#1]
Here they are:
https://github.com/sematext/query-segmenter
https://github.com/sematext/solr-researcher
https://github.com/sematext/solr-autocomplete
https://github.com/sematext/solr-redis
https://github.com/sematext/SearchSchemer

**Comment by tkaessmann** [comment]
Sure! Feel free to submit a pull request.

**Comment by nmtien** [comment]
I create a pull request for this issue here https://github.com/solr-extensions/solr-extensions.github.io/pull/3

**Comment by otisg** [comment]
Thanks!
