### ISSUE TITLE
Docker/Jekyll dependencies issue

### ISSUE THREAD

**Issue by epugh** [solr-extensions/solr-extensions.github.io#11]
```
➜  solr-extensions.github.io git:(master) ✗ docker run --rm \
     --volume="$PWD:/srv/jekyll" \
     -p "4000:4000" \
     -it jekyll/jekyll:3.8 \
     jekyll serve --watch
```

Your bundle is locked to octokit (4.17.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of octokit (4.17.0) has removed it. You'll need to update your bundle to a version other than octokit (4.17.0) that hasn't been removed
in order to install.

**Comment by tboeghk** [comment]
Thanks for raising, but it works for me :-/

Could you verify to launch with a more explicit version of Jekyll. The most recent in the 3.8 branch is 3.8.6:

```
docker run --rm \
     --volume="$PWD:/srv/jekyll" \
     -p "4000:4000" \
     -it jekyll/jekyll:3.8.6 \
     jekyll serve --watch
```

I get:

````
[...]
Installing terminal-table 1.8.0
Fetching github-pages 204
Installing github-pages 204
Bundle complete! 1 Gemfile dependency, 85 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.304 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
    Server address: http://0.0.0.0:4000
```

**Comment by epugh** [comment]
Very odd...     Downloaded the newer version, but still get same error...  

Going to try and rechck things out...

```
➜  solr-extensions.github.io git:(add_solcolator) docker run --rm \
     --volume="$PWD:/srv/jekyll" \
     -p "4000:4000" \
     -it jekyll/jekyll:3.8.6 \
     jekyll serve --watch
Unable to find image 'jekyll/jekyll:3.8.6' locally
3.8.6: Pulling from jekyll/jekyll
Digest: sha256:9521c8aae4739fcbc7137ead19f91841b833d671542f13e91ca40280e88d6e34
Status: Downloaded newer image for jekyll/jekyll:3.8.6
Fetching gem metadata from http://rubygems.org/.........
Your bundle is locked to octokit (4.17.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of octokit (4.17.0) has removed it. You'll need to update your bundle to a version other than octokit (4.17.0) that hasn't been removed
in order to install.

```

**Comment by epugh** [comment]
Found it...  https://github.com/octokit/octokit.rb/releases/tag/v4.17.0

It has been pulled from Rubygems due to issues... 

how do we bump the version to the 4.18.0?

Eric

**Comment by epugh** [comment]
okay, I rechecked out the git repo, and reran docker, and it worked...    The bundle install that happens, i take that the docker image for jekyll doesn't have all the dependencies baked in at image creation time??

**Comment by tboeghk** [comment]
It loads additional dependencies from the `Gemfile`. [But that one's pretty tiny](https://github.com/solr-extensions/solr-extensions.github.io/blob/master/Gemfile)

**Comment by epugh** [comment]
Yeah, and I must have had the broken 4.17.0 locally in my Gemfile.lock.  Seems odd that it runs bundle install at startup time, that should all be baked in the image.

It's working, so we can close.  Thanks for the second set of eyes!!!!!!    See you at virtual BerlinBuzzfest?
