### ISSUE TITLE
Add YASA Solr plugin into solr.cool website

### ISSUE THREAD

**Issue by kezhenxu94** [solr-extensions/solr-extensions.github.io#22]
Hi, I'm wondering whether it's suitable to put the YASA Solr plugin in the website solr.cool, YASA is "Yet Another Solr Admin" that serves in multiple modes to replace the original Solr Admin, you can find more details here: https://github.com/yasa-org/yasa

**Comment by tboeghk** [comment]
@epugh already submitted PR #23 and it's live as of now :-)

**Comment by kezhenxu94** [comment]
Thanks
