### ISSUE TITLE
New Solr extension for your list

### ISSUE THREAD

**Issue by davidbackstein** [solr-extensions/solr-extensions.github.io#6]
Hi there,
I came across your cool solr.cool extension list! Thanks for providing it. We've developed a Solr extension as well which enables users to index images and search them visually. Additionally, it is possible to combine image searches with traditional text based search criteria in one query.

I would be pleased if you are interested in adding our extension to your list.
Some infos:
Docs: https://docs.pixolution.org
License: proprietary
Compatible to Solr 6.x

Let me know what you think.

All the best,
David
company website: https://pixolution.org/

**Comment by tboeghk** [comment]
Thanks for pointing this out. At the moment I'm not sure if we're going to add extensions having a proprietary license. I'll check back. 👍
